---
- name: Install JetBrains Toolbox
  shell: curl -fsSL https://raw.githubusercontent.com/nagygergo/jetbrains-toolbox-install/master/jetbrains-toolbox.sh | bash
  tags:
    - dev
  become: true
  ignore_errors: true
