---
- name: Ensure stow is installed
  ansible.builtin.package:
    name:
      - stow
    state: latest
  become: true
  tags:
    - stow
    - install

- name: Stow dotfiles
  shell: "cd $HOME/.dotfiles/configs ; stow ."
  tags:
    - stow

