---
- name: Ensure stow is installed
  ansible.builtin.package:
    name:
      - stow
    state: latest
  become: true
  tags:
    - stow
    - install


- name: Stow dotfiles
  become: yes
  shell: "stow $HOME/.dotfiles/configs/*"
  with_items: "{{ stow_folders.split(' ') }}"
  tags:
    - stow
