---
- name: "Neovim | Dependencies"
  ansible.builtin.package:
    name:
      - cmake
      - curl
      - ninja-build
      - unzip
      - xclip
      - ripgrep
      - gcc
      - fd-find
      - build-essential
      - gettext
    state: latest
  become: yes

- name: Clone Neovim
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && CMAKE_BUILD_TYPE=RelWithDebInfo && git checkout stable"
  tags:
    - install
    - neovim

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && sudo make install"
  tags:
    - install
    - neovim

- name: "Neovim | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
